use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct RelayReadObservationRecord {
    pub id: String,
    pub relay_url: String,
    pub surface: String,
    pub phase: String,
    pub direction: String,
    pub route_group_key: String,
    pub semantic_feed_key: String,
    pub semantic_filter_key: String,
    pub purpose: String,
    pub started_at_ms: u64,
    pub first_event_ms: Option<u64>,
    pub eose_ms: Option<u64>,
    pub duration_ms: u64,
    pub event_count: u64,
    pub unique_event_count: u64,
    pub final_count: u64,
    pub timeout: bool,
    pub closed: bool,
    pub auth: bool,
    pub socket_error: bool,
    pub event_limit_reached: bool,
    pub bytes_sent: u64,
    pub bytes_received: u64,
    pub route_evidence_sources: Vec<String>,
    pub created_at_ms: u64,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct SqliteRelayReadObservationRow {
    pub id: String,
    pub relay_url: String,
    pub surface: String,
    pub phase: String,
    pub direction: String,
    pub route_group_key: String,
    pub semantic_feed_key: String,
    pub semantic_filter_key: String,
    pub purpose: String,
    pub started_at_ms: u64,
    pub first_event_ms: Option<u64>,
    pub eose_ms: Option<u64>,
    pub duration_ms: u64,
    pub event_count: u64,
    pub unique_event_count: u64,
    pub final_count: u64,
    pub timeout: i64,
    pub closed: i64,
    pub auth: i64,
    pub socket_error: i64,
    pub event_limit_reached: i64,
    pub bytes_sent: u64,
    pub bytes_received: u64,
    pub route_evidence_sources_json: String,
    pub created_at_ms: u64,
}

pub fn sqlite_relay_read_observation_row(
    record: &RelayReadObservationRecord,
) -> Result<SqliteRelayReadObservationRow, serde_json::Error> {
    Ok(SqliteRelayReadObservationRow {
        id: record.id.clone(),
        relay_url: record.relay_url.clone(),
        surface: record.surface.clone(),
        phase: record.phase.clone(),
        direction: record.direction.clone(),
        route_group_key: record.route_group_key.clone(),
        semantic_feed_key: record.semantic_feed_key.clone(),
        semantic_filter_key: record.semantic_filter_key.clone(),
        purpose: record.purpose.clone(),
        started_at_ms: record.started_at_ms,
        first_event_ms: record.first_event_ms,
        eose_ms: record.eose_ms,
        duration_ms: record.duration_ms,
        event_count: record.event_count,
        unique_event_count: record.unique_event_count,
        final_count: record.final_count,
        timeout: i64::from(record.timeout),
        closed: i64::from(record.closed),
        auth: i64::from(record.auth),
        socket_error: i64::from(record.socket_error),
        event_limit_reached: i64::from(record.event_limit_reached),
        bytes_sent: record.bytes_sent,
        bytes_received: record.bytes_received,
        route_evidence_sources_json: serde_json::to_string(&record.route_evidence_sources)?,
        created_at_ms: record.created_at_ms,
    })
}

pub fn relay_read_observation_from_sqlite_row(
    row: &SqliteRelayReadObservationRow,
) -> Result<RelayReadObservationRecord, serde_json::Error> {
    Ok(RelayReadObservationRecord {
        id: row.id.clone(),
        relay_url: row.relay_url.clone(),
        surface: row.surface.clone(),
        phase: row.phase.clone(),
        direction: row.direction.clone(),
        route_group_key: row.route_group_key.clone(),
        semantic_feed_key: row.semantic_feed_key.clone(),
        semantic_filter_key: row.semantic_filter_key.clone(),
        purpose: row.purpose.clone(),
        started_at_ms: row.started_at_ms,
        first_event_ms: row.first_event_ms,
        eose_ms: row.eose_ms,
        duration_ms: row.duration_ms,
        event_count: row.event_count,
        unique_event_count: row.unique_event_count,
        final_count: row.final_count,
        timeout: row.timeout != 0,
        closed: row.closed != 0,
        auth: row.auth != 0,
        socket_error: row.socket_error != 0,
        event_limit_reached: row.event_limit_reached != 0,
        bytes_sent: row.bytes_sent,
        bytes_received: row.bytes_received,
        route_evidence_sources: serde_json::from_str(&row.route_evidence_sources_json)?,
        created_at_ms: row.created_at_ms,
    })
}
