services:
  app:
    build:
      context: .
      target: app
    image: lkjstr-app:local
    environment:
      CI: '1'
    ports:
      - '5173:5173'

  verify:
    build:
      context: .
      target: verify
    image: lkjstr-verify:local
    environment:
      CI: '1'

  e2e:
    build:
      context: .
      target: e2e
    image: lkjstr-e2e:local
    environment:
      CI: '1'
