services:
  app:
    build:
      context: .
      target: app
    image: lkjstr:local
    ports:
      - '5173:5173'

  verify:
    build:
      context: .
      target: verify
    image: lkjstr-verify:local

  cloudflare:
    build:
      context: .
      target: cloudflare
    image: lkjstr-cloudflare:local

  e2e:
    build:
      context: .
      target: e2e
    image: lkjstr-e2e:local
