import type { StorageTableSpec } from './table-spec';
import { ledgerTable, table } from './table-builders';

export const storageTableSpecs = [
  table('workspaces', 'protected-user-data', 'protected', 'workspace', true),
  table('accounts', 'protected-user-data', 'protected', 'accounts', true),
  table(
    'localAccountSecrets',
    'protected-user-data',
    'protected',
    'signer',
    true,
  ),
  ledgerTable(
    'notifications',
    'recoverable-cache',
    'prunable-cache',
    'notifications',
    'notification-record',
  ),
  table('tweetDrafts', 'protected-user-data', 'protected', 'tweet', true),
  ledgerTable(
    'events',
    'recoverable-cache',
    'prunable-cache',
    'events',
    'nostr-event',
  ),
  table('cacheLedger', 'ledger', 'ledger', 'storage', false),
  ledgerTable(
    'eventRelays',
    'recoverable-cache',
    'prunable-cache',
    'events',
    'nostr-event',
  ),
  ledgerTable(
    'eventTags',
    'recoverable-cache',
    'prunable-cache',
    'events',
    'nostr-event',
  ),
  ledgerTable(
    'feedCursors',
    'derived-feed-cache',
    'derived-page-cache',
    'feeds',
    'feed-cursor',
  ),
  ledgerTable(
    'feedCoverage',
    'derived-feed-cache',
    'derived-page-cache',
    'feeds',
    'coverage-row',
  ),
  ledgerTable(
    'feedScanHints',
    'derived-feed-cache',
    'derived-page-cache',
    'feeds',
    'scan-hint',
  ),
  ledgerTable(
    'jobs',
    'recoverable-cache',
    'prunable-cache',
    'jobs',
    'job-record',
  ),
  table('cacheMeta', 'metadata', 'metadata', 'storage', false),
  ledgerTable(
    'tabStates',
    'protected-user-data',
    'protected',
    'workspace',
    'tab-state',
    true,
  ),
  table('settings', 'protected-user-data', 'protected', 'settings', true),
  table('relaySets', 'protected-user-data', 'protected', 'relays', true),
  ledgerTable(
    'relayDiagnosticSummaries',
    'diagnostics-cache',
    'diagnostics',
    'relays',
    'relay-summary',
  ),
  ledgerTable(
    'relayInformation',
    'diagnostics-cache',
    'diagnostics',
    'relays',
    'relay-info',
  ),
  ledgerTable(
    'relayListSuggestions',
    'diagnostics-cache',
    'diagnostics',
    'relays',
    'relay-list-suggestion',
  ),
  ledgerTable(
    'authorRelayRoutes',
    'diagnostics-cache',
    'diagnostics',
    'relays',
    'author-relay-route',
  ),
  table(
    'relayRouteBlocks',
    'protected-safety-configuration',
    'protected-safety',
    'relays',
    true,
  ),
] as const satisfies readonly StorageTableSpec[];
