import type { StorageTableSpec } from './table-spec';
import { ledgerTable, table } from './table-builders';

export const storageTableSpecs = [
  table(
    'workspaces',
    '&id, updatedAt, activeAccountId',
    'protected-user-data',
    'protected',
    'workspace',
    true,
  ),
  table(
    'accounts',
    '&id, pubkey, signerType, updatedAt, lastUsedAt',
    'protected-user-data',
    'protected',
    'accounts',
    true,
  ),
  table(
    'localAccountSecrets',
    '&accountId, pubkey, updatedAt',
    'protected-user-data',
    'protected',
    'signer',
    true,
  ),
  ledgerTable(
    'notifications',
    '&id, accountPubkey, sourceEventId, actorPubkey, kind, readAt, createdAt, [accountPubkey+createdAt]',
    'recoverable-cache',
    'prunable-cache',
    'notifications',
    'notification-record',
  ),
  table(
    'tweetDrafts',
    '&id, accountId, updatedAt',
    'protected-user-data',
    'protected',
    'tweet',
    true,
  ),
  ledgerTable(
    'events',
    '&id, pubkey, kind, created_at, [kind+created_at], [pubkey+kind+created_at]',
    'recoverable-cache',
    'prunable-cache',
    'events',
    'nostr-event',
  ),
  table(
    'cacheLedger',
    '&id, ownerKind, resourceKind, resourceId, score, createdAt, updatedAt, protected, accountPubkey, feedKey, relayUrl, [protected+score], [ownerKind+score], [resourceKind+score]',
    'ledger',
    'ledger',
    'storage',
    false,
  ),
  ledgerTable(
    'eventRelays',
    '&id, eventId, relayUrl, receivedAt',
    'recoverable-cache',
    'prunable-cache',
    'events',
    'nostr-event',
  ),
  ledgerTable(
    'eventTags',
    '&id, eventId, tagName, tagValue, created_at, [tagName+tagValue], [tagName+tagValue+created_at]',
    'recoverable-cache',
    'prunable-cache',
    'events',
    'nostr-event',
  ),
  ledgerTable(
    'feedCursors',
    '&id, feedKey, updatedAt',
    'derived-feed-cache',
    'derived-page-cache',
    'feeds',
    'feed-cursor',
  ),
  ledgerTable(
    'feedCoverage',
    '&id, feedKey, relayUrl, groupKey, status, updatedAt, [feedKey+status], [feedKey+relayUrl], [feedKey+groupKey], [feedKey+updatedAt]',
    'derived-feed-cache',
    'derived-page-cache',
    'feeds',
    'coverage-row',
  ),
  ledgerTable(
    'feedScanHints',
    '&id, scanKey, relayUrl, groupKey, filterKey, direction, updatedAt, [scanKey+direction], [scanKey+relayUrl]',
    'derived-feed-cache',
    'derived-page-cache',
    'feeds',
    'scan-hint',
  ),
  ledgerTable(
    'jobs',
    '&id, rootId, parentId, kind, status, updatedAt, [rootId+updatedAt]',
    'recoverable-cache',
    'prunable-cache',
    'jobs',
    'job-record',
  ),
  table(
    'cacheMeta',
    '&id, updatedAt',
    'metadata',
    'metadata',
    'storage',
    false,
  ),
  ledgerTable(
    'tabStates',
    '&id, workspaceId, tabId, lastPaneId, updatedAt',
    'protected-user-data',
    'protected',
    'workspace',
    'tab-state',
    true,
  ),
  table(
    'settings',
    '&key, namespace, updatedAt',
    'protected-user-data',
    'protected',
    'settings',
    true,
  ),
  table(
    'relaySets',
    '&id, updatedAt, seeded',
    'protected-user-data',
    'protected',
    'relays',
    true,
  ),
  ledgerTable(
    'relayDiagnosticSummaries',
    '&relayUrl, updatedAt',
    'diagnostics-cache',
    'diagnostics',
    'relays',
    'relay-summary',
  ),
  ledgerTable(
    'relayInformation',
    '&relayUrl, fetchedAt, status',
    'diagnostics-cache',
    'diagnostics',
    'relays',
    'relay-info',
  ),
  ledgerTable(
    'relayListSuggestions',
    '&id, accountPubkey, relayUrl, updatedAt, [accountPubkey+relayUrl]',
    'diagnostics-cache',
    'diagnostics',
    'relays',
    'relay-list-suggestion',
  ),
  ledgerTable(
    'authorRelayRoutes',
    '&id, authorPubkey, relayUrl, source, updatedAt, [authorPubkey+relayUrl]',
    'diagnostics-cache',
    'diagnostics',
    'relays',
    'author-relay-route',
  ),
  table(
    'relayRouteBlocks',
    '&relayUrl, reason, updatedAt',
    'protected-safety-configuration',
    'protected-safety',
    'relays',
    true,
  ),
] as const satisfies readonly StorageTableSpec[];
