import type { DemandVisibility } from '../relays/orchestration/demand-types';
import type { SubscriptionOrchestrator } from '../relays/orchestration/orchestrator';
import type { FeedCursorPoint } from '../events/types';
import type { TimelineLoad } from './timeline-load';
import type { TimelineState } from './timeline-state';
import type { TimelineItem } from './timeline-store';

export type TimelineNetworkCtx = {
  readonly surface: 'home' | 'global';
  readonly owner: string;
  readonly subscriptions: SubscriptionOrchestrator;
  readonly relays: readonly string[];
  readonly pageSize: number;
  readonly noteSubId: string;
  readonly metaSubId: string;
  readonly followSubId: string;
  readonly setProfiles: (v: TimelineState['profiles']) => void;
  readonly startedAt: number;
  readonly activeAccountPubkey?: string | null;
  readonly cleanup: () => (() => void)[];
  readonly signal: AbortSignal;
  readonly visibility: () => DemandVisibility;
  readonly isClosed: () => boolean;
  readonly isActive: (run: number) => boolean;
  readonly getGeneration: () => number;
  readonly items: () => TimelineItem[];
  readonly getState: () => TimelineState;
  readonly emit: (next: TimelineState) => void;
  readonly nextState: (patch: Partial<TimelineState>) => TimelineState;
  readonly getAuthors: () => string[];
  readonly setAuthors: (v: string[]) => void;
  readonly getProfiles: () => TimelineState['profiles'];
  readonly getFollowList: () => TimelineLoad['followList'];
  readonly setFollowList: (v: TimelineLoad['followList']) => void;
  readonly getFollowListId: () => string;
  readonly setFollowListId: (v: string) => void;
  readonly setFollowFallbackStarted: (v: boolean) => void;
  readonly getFollowFallbackStarted: () => boolean;
  readonly getCached: () => TimelineItem[];
  readonly setCached: (v: TimelineItem[]) => void;
  readonly clearLive: () => void;
  readonly getOlderScanCursor: () => FeedCursorPoint | undefined;
  readonly setOlderScanCursor: (v: FeedCursorPoint | undefined) => void;
  readonly getInitialNotesKey: () => string;
  readonly setInitialNotesKey: (v: string) => void;
  readonly getRouteRefreshGeneration: () => number;
  readonly setRouteRefreshGeneration: (v: number) => void;
  readonly applyLoaded: (loaded: TimelineLoad) => void;
  readonly withCursors: (next: TimelineState) => TimelineState;
  readonly setLive: (v: TimelineItem[]) => void;
  readonly getLive: () => TimelineItem[];
};
